### ISSUE TITLE
HOME Page 

### ISSUE THREAD

**Issue by seditiouslassie** [abbasidaniyal/PlasmaDonorFinder#11]
HOME Page: Let us address the donors directly. Sell it as HELP INDIA FIGHT COVID-19 INFECTION IN JUST 3 Steps. 
If you are a covid-19 recovered patient, then: 

**STEP 1.** : Register as a donor. 

**STEP 2** : Update your LOCATION (via pincode, maps, coordinates), IGG documents and COVID-19 reports. 

**STEP 3** : Nearest hospital will contact you based on your pincode. 

(this can be represented as a creative diagram, infographic, flow chart something that makes people less scared of this whole thing)

**Comment by zrthxn** [comment]
If you can make one of those 2d orthogonal type graphics like [this](https://prismberry.com/img/for4.png) to represent this information flow it can be added to the homepage.

Although I've mostly seen those types of things on business related websites like [PayU and stuff](https://www.payu.in/)

**Comment by seditiouslassie** [comment]
Let me see if I can understand how to make that.
