### ISSUE TITLE
FREQUENTLY ASKED QUESTIONS 

### ISSUE THREAD

**Issue by seditiouslassie** [abbasidaniyal/PlasmaDonorFinder#12]
I think it will make a lot of sense to have a frequently asked questions page. This will not only cover what is plasma therapy, what do you have to do as a donor, what does the latest on plasma therapy for COVID-19 says in India, contact ICMR documents, explain to donors why this would help the country and also cover legal aspects of the website: as in who gets access to the location, IGG reports and other private information of the donors.

**Comment by abbasidaniyal** [comment]
Create model with question and answer field (both TextField) and use simple ListView

**Comment by abbasidaniyal** [comment]
@omairk
