### ISSUE TITLE
Migrate gives error 'DatabaseOperations' object has no attribute 'geo_db_type'

### ISSUE THREAD

**Issue by zrthxn** [abbasidaniyal/PlasmaDonorFinder#13]
After installation from the requirements and after running **makemigrations**
```shell
$ python manage.py makemigrations
```

when I try to run the **migrate** migrate command, I get the following error (traceback is included)
```shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, users
Running migrations:
  Applying users.0001_initial...Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)

 .....

    type_string = self.db_type(connection)
  File "/home/zrthxn/.local/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 105, in db_type
    return connection.ops.geo_db_type(self)
AttributeError: 'DatabaseOperations' object has no attribute 'geo_db_type'
```

Now I don't know if I'm missing a package or what

**Comment by abbasidaniyal** [comment]
This must be occurring due to the environment variables. Try hardcoding the values to see if it fixes it

**Comment by zrthxn** [comment]
**[SOLVED]**
Okay so this turned out to be a PostGIS issue.
I tried to hardcode the values from the .env file and it gave the following error
```shell
$ python manage.py migrate
Traceback (most recent call last):
  File "/home/zrthxn/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
....
    return self.cursor.execute(sql)
django.db.utils.OperationalError: could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
```

So I tried to reinstall PostgreSQL 10

**Comment by zrthxn** [comment]
**[SOLVED]**

Okay so this turned out to be a PostGIS issue.
I tried to hardcode the values from the .env file and it gave the following error
```shell
$ python manage.py migrate
Traceback (most recent call last):
  File "/home/zrthxn/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
....
    return self.cursor.execute(sql)
django.db.utils.OperationalError: could not open extension control file 
"/usr/share/postgresql/10/extension/postgis.control": No such file or directory
```

Apparently the missing control file was a big issue so I tried to reinstall PostGIS
```shell
$ sudo apt-get install postgis*
```
The asterisk (*) means that apt-get will automatically get the right package versions. So this operation reinstalled PostgreSQL 10 from scratch.

Then I created a new User and DB on the new installation 
```shell
$ sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
$ sudo -u postgres psql -c "CREATE DATABASE testdb;"
```

Then I used the username and password *postgres* as the hardcoded values in the settings.py file and the migrate operation ran fine.
