### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by seditiouslassie** [abbasidaniyal/PlasmaDonorFinder#18]
I guess three of us are working on this as of now, then we should make a team page. With maybe a few lines about us, our email IDs and twitter/instagram account to further let people contact us. This will help them know that we are normal people and validate the page.

**Comment by zrthxn** [comment]
Team section added to homepage with template images

**Comment by abbasidaniyal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Every team member send photo and contact details](https://trello.com/c/2CESss1Q/12-every-team-member-send-photo-and-contact-details)
