### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by abbasidaniyal** [abbasidaniyal/PlasmaDonorFinder#25]
Look for other samples from undraw.co which are more relatable to the website for the hero image. 
It is looking really good so we should try to find something similar.

**Comment by abbasidaniyal** [comment]
@zrthxn Thoughts?

**Comment by zrthxn** [comment]
Yea that can be done although we wouldn't want to make it look too "artistic". In my experience professionals appreciate a more **serious** look.

**Comment by abbasidaniyal** [comment]
Makes sense. Let me know if you find something interesting
