### ISSUE TITLE
Model Testing and View Testing

### ISSUE THREAD

**Issue by zrthxn** [abbasidaniyal/PlasmaDonorFinder#26]
There are quite a few places where the code breaks when invalid input is entered. An example of this is that any user gets a valid login token even if the signup process fails. 

I suggest we write some tests for the code that's written for the users app especially since an alpha is supposed to be ready soon.
More tests can be written later on with the progress of the project.

If yes then I could help with that

**Comment by abbasidaniyal** [comment]
Yes we need a lot of testing.
Can you also tell me who to reproduce the error you mentioned?

**Comment by zrthxn** [comment]
Unfortunately I can't remember what exactly I did but it involved the signup form. I've closed the issue I made for that but I'll reopen it if I find out.

**Comment by abbasidaniyal** [comment]
Alrigthy!

**Comment by abbasidaniyal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TESTS and code coverage](https://trello.com/c/emZ6qVwk/18-tests-and-code-coverage)
