### ISSUE TITLE
AttributeError at /users/password_reset/ 

### ISSUE THREAD

**Issue by zrthxn** [abbasidaniyal/PlasmaDonorFinder#31]
The following error is encountered when trying to reset password
```shell
AttributeError at /users/password_reset/
'tuple' object has no attribute 'encode'
```
### Steps to reproduce
- Go to /users/password_reset/ 
- Enter your email address which should already exist in the db
- et voila

**Comment by abbasidaniyal** [comment]
https://github.com/abbasidaniyal/PlasmaDonorFinder/commit/1a0a7d439743feb1d9952bfa5576ed3683b337d9 fixes this
