### ISSUE TITLE
Hospital Verification

### ISSUE THREAD

**Issue by abbasidaniyal** [abbasidaniyal/PlasmaDonorFinder#32]
Should we stick with the simple email verification for the hospital or add an additional filter and manually verify the hospitals? 
Since hospitals can access private data of the donors, I believe we should add another layer of security. 

Workflow :
1. Hospitals Register
2. Hospitals complete their profile
3. DO NOT MAKE IS COMPLETE TRUE HERE https://github.com/abbasidaniyal/PlasmaDonorFinder/blob/master/users/views.py#L115
Another thing we can do is, we can also use a new boolean -> `is_verified` to keep a track of the verified hospitals.

4. Admin panel must have the option to set is_verified as true after manual verification.

**Comment by seditiouslassie** [comment]
Hmm, maybe that might be a good idea. But how do you plan on going about this? Maybe if they confirm their phone numbers then they will need to be contacted.

**Comment by abbasidaniyal** [comment]
We can start with manual verification like by seeing the Registration number etc. 
Later we will try to automate that part

**Comment by seditiouslassie** [comment]
I'll speak to father and see if there is anyway of verifying for this. Maybe there is a document that we can ask them to verify as well.
