### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by abbasidaniyal** [abbasidaniyal/PlasmaDonorFinder#33]
The FAQs are listed in random order. 
Either we add a `ordering` parameter to the models and specify the range of FAQs and their respective positions.

Or, sort the FAQs depending on the time they were added in reverse order.

**Comment by zrthxn** [comment]
Why not make them static on the template? FAQs don't tend to change all that often

**Comment by abbasidaniyal** [comment]
Not bad. It'll be hard to update just in case 😞 
Others tell?

**Comment by zrthxn** [comment]
Not that hard really...
Or we could use a CMS to manage all the content
